import type { BuddyProfile } from '../types/buddy';

export const MOCK_BUDDIES: BuddyProfile[] = [
  {
    id: 'buddy_01',
    name: '林小美',
    avatar: '🌸',
    city: '上海',
    gender: 'female',
    age: 24,
    interests: ['Taylor Swift', 'K-pop', '摄影'],
    purpose: ['拼房', '一起排队', '互相照应'],
    travelStyle: ['舒适型', '打卡型'],
    matchPercentage: 92,
    isFriend: false,
    bio: '追星十年老粉，一起看演唱会呀～',
    nameEn: 'Lin Xiaomei',
    cityEn: 'Shanghai',
    interestsEn: ['Taylor Swift', 'K-pop', 'Photography'],
    purposeEn: ['Share hotel', 'Queue together', 'Look out for each other'],
    travelStyleEn: ['Comfortable', 'Check-in style'],
    bioEn: 'Been a fan for 10 years, let\'s go to concerts together~',
  },
  {
    id: 'buddy_02',
    name: '张一鸣',
    avatar: '🎵',
    city: '北京',
    gender: 'male',
    age: 27,
    interests: ['周杰伦', '话剧', '桌游'],
    purpose: ['拼车', '交流心得'],
    travelStyle: ['经济型', '深度体验'],
    matchPercentage: 85,
    isFriend: false,
    bio: '音乐剧爱好者，周末喜欢看演出',
    nameEn: 'Zhang Yiming',
    cityEn: 'Beijing',
    interestsEn: ['Jay Chou', 'Drama', 'Board Games'],
    purposeEn: ['Share ride', 'Share experiences'],
    travelStyleEn: ['Budget-friendly', 'Deep experience'],
    bioEn: 'Musical lover, I enjoy watching shows on weekends',
  },
  {
    id: 'buddy_03',
    name: '王思睿',
    avatar: '🎸',
    city: '深圳',
    gender: 'male',
    age: 26,
    interests: ['摇滚', '音乐节', '露营'],
    purpose: ['拼房', '拼车', '拍照互助'],
    travelStyle: ['特种兵', '经济型'],
    matchPercentage: 78,
    isFriend: false,
    bio: '吉他手，各大音乐节常客',
    nameEn: 'Wang Sirui',
    cityEn: 'Shenzhen',
    interestsEn: ['Rock', 'Music Festival', 'Camping'],
    purposeEn: ['Share hotel', 'Share ride', 'Photo help'],
    travelStyleEn: ['Intensive', 'Budget-friendly'],
    bioEn: 'Guitarist, regular at music festivals',
  },
  {
    id: 'buddy_04',
    name: '李雨桐',
    avatar: '📸',
    city: '广州',
    gender: 'female',
    age: 23,
    interests: ['脱口秀', '美食', '旅行'],
    purpose: ['一起排队', '拍照互助', '交流心得'],
    travelStyle: ['舒适型', '深度体验'],
    matchPercentage: 88,
    isFriend: false,
    bio: '笑果文化铁粉，广深演出都追',
    nameEn: 'Li Yutong',
    cityEn: 'Guangzhou',
    interestsEn: ['Comedy', 'Food', 'Travel'],
    purposeEn: ['Queue together', 'Photo help', 'Share experiences'],
    travelStyleEn: ['Comfortable', 'Deep experience'],
    bioEn: 'Xiaoguo Comedy fan, I follow shows in Guangzhou and Shenzhen',
  },
  {
    id: 'buddy_05',
    name: '陈晓',
    avatar: '🎭',
    city: '成都',
    gender: 'female',
    age: 25,
    interests: ['话剧', '音乐剧', '舞蹈'],
    purpose: ['互相照应', '交流心得'],
    travelStyle: ['佛系', '深度体验'],
    matchPercentage: 96,
    isFriend: false,
    bio: '戏剧爱好者，每周末泡剧场',
    nameEn: 'Chen Xiao',
    cityEn: 'Chengdu',
    interestsEn: ['Drama', 'Musical', 'Dance'],
    purposeEn: ['Look out for each other', 'Share experiences'],
    travelStyleEn: ['Chill', 'Deep experience'],
    bioEn: 'Theatre enthusiast, at the theatre every weekend',
  },
  {
    id: 'buddy_06',
    name: '刘浩然',
    avatar: '⚽',
    city: '杭州',
    gender: 'male',
    age: 28,
    interests: ['体育赛事', '电竞', '健身'],
    purpose: ['拼车', '一起排队'],
    travelStyle: ['经济型', '特种兵'],
    matchPercentage: 72,
    isFriend: false,
    bio: 'NBA和LOL都看，运动达人',
    nameEn: 'Liu Haoran',
    cityEn: 'Hangzhou',
    interestsEn: ['Sports', 'Esports', 'Fitness'],
    purposeEn: ['Share ride', 'Queue together'],
    travelStyleEn: ['Budget-friendly', 'Intensive'],
    bioEn: 'NBA and LOL fan, fitness enthusiast',
  },
  {
    id: 'buddy_07',
    name: '赵雪儿',
    avatar: '🎤',
    city: '香港',
    gender: 'female',
    age: 22,
    interests: ['陈奕迅', '粤语歌', '甜品'],
    purpose: ['拼房', '互相照应', '拍照互助'],
    travelStyle: ['舒适型', '打卡型'],
    matchPercentage: 90,
    isFriend: false,
    bio: '广东歌爱好者，红馆常客',
    nameEn: 'Zhao Xue\'er',
    cityEn: 'Hong Kong',
    interestsEn: ['Eason Chan', 'Cantopop', 'Desserts'],
    purposeEn: ['Share hotel', 'Look out for each other', 'Photo help'],
    travelStyleEn: ['Comfortable', 'Check-in style'],
    bioEn: 'Cantonese music lover, regular at Hong Kong Coliseum',
  },
  {
    id: 'buddy_08',
    name: '黄子轩',
    avatar: '🎹',
    city: '南京',
    gender: 'male',
    age: 29,
    interests: ['古典乐', '爵士', '咖啡'],
    purpose: ['交流心得', '一起排队'],
    travelStyle: ['佛系', '深度体验'],
    matchPercentage: 82,
    isFriend: false,
    bio: '钢琴老师，对各种演出都感兴趣',
    nameEn: 'Huang Zixuan',
    cityEn: 'Nanjing',
    interestsEn: ['Classical', 'Jazz', 'Coffee'],
    purposeEn: ['Share experiences', 'Queue together'],
    travelStyleEn: ['Chill', 'Deep experience'],
    bioEn: 'Piano teacher, interested in all kinds of performances',
  },
];
