export const VENUES_BY_CITY: Record<string, string[]> = {
  '北京': [
    '国家体育场（鸟巢）',
    '国家游泳中心（水立方）',
    '凯迪拉克中心',
    '国家大剧院',
    '工人体育场',
    '北京国家体育馆',
    '五棵松体育馆',
    '首都体育馆',
    '北京展览馆剧场',
  ],
  '上海': [
    '梅赛德斯-奔驰文化中心',
    '上海体育场（八万人体育场）',
    '上海体育馆',
    '上海东方体育中心',
    '国家会展中心（上海）',
    '上海大剧院',
    '上海文化广场',
    '上海保利大剧院',
  ],
  '广州': [
    '广州天河体育中心',
    '广州体育馆',
    '广州宝能观致文化中心',
    '广州国际体育演艺中心',
    '广州大剧院',
    '广州中山纪念堂',
  ],
  '深圳': [
    '深圳湾体育中心（春茧）',
    '深圳大运中心体育馆',
    '深圳世界之窗',
    '深圳体育馆',
    '深圳保利剧院',
    '深圳华夏艺术中心',
  ],
  '成都': [
    '成都金融城演艺中心',
    '成都东安湖体育公园',
    '成都大魔方演艺中心',
    '成都体育中心',
    '成都城市音乐厅',
    '成都五粮液体育中心',
  ],
  '杭州': [
    '杭州奥体中心（大莲花）',
    '黄龙体育中心',
    '杭州体育馆',
    '杭州大剧院',
    '杭州酒球会',
  ],
  '武汉': [
    '武汉体育中心',
    '武汉光谷国际网球中心',
    '武汉琴台大剧院',
    '武汉客厅·中国文化博览中心',
  ],
  '南京': [
    '南京奥体中心',
    '南京青奥体育公园',
    '南京保利大剧院',
    '南京太阳宫',
  ],
  '重庆': [
    '重庆华熙LIVE·鱼洞',
    '重庆国际博览中心',
    '重庆大剧院',
    '重庆人民大礼堂',
  ],
  '长沙': [
    '湖南国际会展中心',
    '长沙贺龙体育中心',
    '长沙梅溪湖国际文化艺术中心',
    '长沙国际会展中心',
  ],
  '天津': [
    '天津奥林匹克中心体育场（水滴）',
    '天津体育馆',
    '天津大剧院',
    '天津国家会展中心',
  ],
  '西安': [
    '西安奥体中心',
    '西安城市运动公园',
    '西安曲江国际会展中心',
    '西安音乐厅',
  ],
  '香港': [
    '红磡体育馆',
    '香港会议展览中心',
    '亚洲国际博览馆',
    '香港文化中心',
  ],
  '台北': [
    '台北小巨蛋',
    '台北流行音乐中心',
    '台北国际会议中心',
    '台北华山1914文化创意产业园区',
  ],
  '东京': [
    '东京巨蛋',
    '日本武道馆',
    '国立竞技场',
    '埼玉超级竞技场',
    '有明竞技场',
    '横滨体育馆',
  ],
  '大阪': [
    '大阪京瓷巨蛋',
    '大阪城展演厅',
    'Zepp 难波',
    'Grand Cube 大阪',
  ],
  '首尔': [
    '首尔奥林匹克体育场',
    '首尔蚕室综合运动场',
    '高尺天空巨蛋',
    '首尔奥林匹克公园',
    '首尔BLUESQUARE',
  ],
  '曼谷': [
    'Impact 竞技场',
    'Rajamangala 国家体育场',
    '曼谷文化中心',
    '曼谷Royal Paragon Hall',
  ],
  '新加坡': [
    '新加坡室内体育馆',
    '新加坡国家体育场',
    '滨海艺术中心',
    '金沙会议展览中心',
  ],
  '苏州': [
    '苏州奥体中心体育馆',
    '苏州文化艺术中心',
    '苏州保利大剧院',
    '苏州体育中心体育场',
  ],
  '厦门': [
    '厦门嘉庚体育馆',
    '厦门国际会展中心',
    '厦门闽南大戏院',
    '厦门体育中心体育场',
  ],
  '青岛': [
    '青岛国信体育馆',
    '青岛体育中心国信体育场',
    '青岛大剧院',
    '青岛凤凰之声大剧院',
  ],
  '大连': [
    '大连体育中心体育馆',
    '大连大剧院',
    '大连国际会议中心大剧院',
    '大连星海广场',
  ],
  '昆明': [
    '昆明滇池国际会展中心',
    '昆明新亚洲体育城',
    '昆明胜利堂剧院',
    '昆明海埂会堂',
  ],
  '郑州': [
    '郑州奥林匹克体育中心',
    '郑州国际会展中心',
    '郑州大剧院',
    '郑州河南省体育中心',
  ],
  '沈阳': [
    '沈阳奥林匹克体育中心',
    '沈阳盛京大剧院',
    '沈阳辽宁体育馆',
    '沈阳国际展览中心',
  ],
  '宁波': [
    '宁波奥体中心体育馆',
    '宁波文化广场大剧院',
    '宁波体育中心体育场',
    '宁波逸夫剧院',
  ],
  '珠海': [
    '珠海国际航展中心',
    '珠海大剧院（日月贝）',
    '珠海体育中心体育场',
    '珠海华发中演大剧院',
  ],
  '佛山': [
    '佛山国际体育文化演艺中心',
    '佛山岭南明珠体育馆',
    '佛山南海体育馆',
    '佛山琼花大剧院',
  ],
  '澳门': [
    '澳门威尼斯人金光综艺馆',
    '澳门新濠影汇综艺馆',
    '澳门文化中心',
    '澳门百老汇舞台',
  ],
  '吉隆坡': [
    '吉隆坡国家体育场',
    '亚通体育馆',
    '吉隆坡会展中心',
    '马来西亚国家剧院',
  ],
  '纽约': [
    '麦迪逊广场花园',
    '巴克莱中心',
    '无线电城音乐厅',
    '林肯中心',
    '阿波罗剧院',
  ],
  '洛杉矶': [
    '斯台普斯中心（Crypto.com竞技场）',
    '好莱坞碗',
    '道奇体育场',
    '微软剧院',
    '论坛体育馆',
  ],
  '伦敦': [
    'O2 体育馆',
    '温布利体育馆',
    '皇家阿尔伯特音乐厅',
    '伦敦体育场',
  ],
  '巴黎': [
    '巴黎雅高竞技场',
    '巴黎拉德芳斯体育馆',
    '巴黎奥林匹亚音乐厅',
    '巴黎塞纳河音乐厅',
  ],
  '悉尼': [
    '悉尼奥林匹克公园',
    '悉尼歌剧院',
    '悉尼国际会议中心',
    '悉尼恩摩剧场',
  ],
};

// English venue translations
export const VENUE_EN: Record<string, string> = {
  '国家体育场（鸟巢）': "National Stadium (Bird's Nest)",
  '国家游泳中心（水立方）': 'National Aquatics Center (Water Cube)',
  '凯迪拉克中心': 'Cadillac Arena',
  '国家大剧院': 'National Centre for the Performing Arts',
  '工人体育场': "Workers' Stadium",
  '北京国家体育馆': 'Beijing National Indoor Stadium',
  '五棵松体育馆': 'Wukesong Arena',
  '首都体育馆': 'Capital Indoor Stadium',
  '北京展览馆剧场': 'Beijing Exhibition Center Theatre',
  '梅赛德斯-奔驰文化中心': 'Mercedes-Benz Arena',
  '上海体育场（八万人体育场）': "Shanghai Stadium (80,000-seat)",
  '上海体育馆': 'Shanghai Indoor Stadium',
  '上海东方体育中心': 'Shanghai Oriental Sports Center',
  '国家会展中心（上海）': 'National Exhibition and Convention Center (Shanghai)',
  '上海大剧院': 'Shanghai Grand Theatre',
  '上海文化广场': 'Shanghai Cultural Square',
  '上海保利大剧院': 'Shanghai Poly Grand Theatre',
  '广州天河体育中心': 'Guangzhou Tianhe Sports Center',
  '广州体育馆': 'Guangzhou Gymnasium',
  '广州宝能观致文化中心': 'Guangzhou Baoneng Guanchi Cultural Center',
  '广州国际体育演艺中心': 'Guangzhou International Sports Arena',
  '广州大剧院': 'Guangzhou Opera House',
  '广州中山纪念堂': 'Sun Yat-sen Memorial Hall',
  '深圳湾体育中心（春茧）': "Shenzhen Bay Sports Center (Spring Cocoon)",
  '深圳大运中心体育馆': 'Shenzhen Universiade Sports Centre',
  '深圳世界之窗': 'Window of the World',
  '深圳体育馆': 'Shenzhen Gymnasium',
  '深圳保利剧院': 'Shenzhen Poly Theatre',
  '深圳华夏艺术中心': 'Shenzhen Huaxia Art Center',
  '成都金融城演艺中心': 'Chengdu Financial City Performing Arts Center',
  '成都东安湖体育公园': 'Chengdu Dongan Lake Sports Park',
  '成都大魔方演艺中心': 'Chengdu Grand Magic Cube',
  '成都体育中心': 'Chengdu Sports Center',
  '成都城市音乐厅': 'Chengdu City Concert Hall',
  '成都五粮液体育中心': 'Chengdu Wuliangye Sports Center',
  '杭州奥体中心（大莲花）': "Hangzhou Olympic Sports Center (Big Lotus)",
  '黄龙体育中心': 'Yellow Dragon Sports Center',
  '杭州体育馆': 'Hangzhou Gymnasium',
  '杭州大剧院': 'Hangzhou Grand Theatre',
  '杭州酒球会': 'Jiuqiuhui (Hangzhou)',
  '武汉体育中心': 'Wuhan Sports Center',
  '武汉光谷国际网球中心': 'Wuhan Optics Valley International Tennis Center',
  '武汉琴台大剧院': 'Wuhan Qintai Grand Theatre',
  '武汉客厅·中国文化博览中心': "Wuhan Living Room · China Cultural Expo Center",
  '南京奥体中心': 'Nanjing Olympic Sports Center',
  '南京青奥体育公园': 'Nanjing Youth Olympic Sports Park',
  '南京保利大剧院': 'Nanjing Poly Grand Theatre',
  '南京太阳宫': 'Nanjing Sun Palace',
  '重庆华熙LIVE·鱼洞': 'Huaxi LIVE·Yudong',
  '重庆国际博览中心': 'Chongqing International Expo Center',
  '重庆大剧院': 'Chongqing Grand Theatre',
  '重庆人民大礼堂': "Chongqing People's Grand Hall",
  '湖南国际会展中心': 'Hunan International Convention Center',
  '长沙贺龙体育中心': 'Changsha Helong Sports Center',
  '长沙梅溪湖国际文化艺术中心': 'Changsha Meixihu International Culture & Art Center',
  '长沙国际会展中心': 'Changsha International Convention Center',
  '天津奥林匹克中心体育场（水滴）': "Tianjin Olympic Center Stadium (Water Drop)",
  '天津体育馆': 'Tianjin Gymnasium',
  '天津大剧院': 'Tianjin Grand Theatre',
  '天津国家会展中心': 'Tianjin National Convention Center',
  '西安奥体中心': "Xi'an Olympic Sports Center",
  '西安城市运动公园': "Xi'an City Sports Park",
  '西安曲江国际会展中心': "Xi'an Qujiang International Expo Center",
  '西安音乐厅': "Xi'an Concert Hall",
  '红磡体育馆': 'Hong Kong Coliseum',
  '香港会议展览中心': 'Hong Kong Convention and Exhibition Centre',
  '亚洲国际博览馆': 'AsiaWorld-Expo',
  '香港文化中心': 'Hong Kong Cultural Centre',
  '台北小巨蛋': 'Taipei Arena',
  '台北流行音乐中心': 'Taipei Music Center',
  '台北国际会议中心': 'Taipei International Convention Center',
  '台北华山1914文化创意产业园区': "Huashan 1914 Creative Park",
  '东京巨蛋': 'Tokyo Dome',
  '日本武道馆': 'Nippon Budokan',
  '国立竞技场': 'National Stadium (Japan)',
  '埼玉超级竞技场': 'Saitama Super Arena',
  '有明竞技场': 'Ariake Arena',
  '横滨体育馆': 'Yokohama Arena',
  '大阪京瓷巨蛋': 'Kyocera Dome Osaka',
  '大阪城展演厅': 'Osaka-jō Hall',
  'Zepp 难波': 'Zepp Namba',
  'Grand Cube 大阪': 'Grand Cube Osaka',
  '首尔奥林匹克体育场': 'Seoul Olympic Stadium',
  '首尔蚕室综合运动场': 'Seoul Jamsil Sports Complex',
  '高尺天空巨蛋': 'Gocheok Sky Dome',
  '首尔奥林匹克公园': 'Seoul Olympic Park',
  '首尔BLUESQUARE': 'BLUESQUARE (Seoul)',
  'Impact 竞技场': 'Impact Arena',
  'Rajamangala 国家体育场': 'Rajamangala National Stadium',
  '曼谷文化中心': 'Bangkok Cultural Centre',
  '曼谷Royal Paragon Hall': 'Royal Paragon Hall',
  '新加坡室内体育馆': 'Singapore Indoor Stadium',
  '新加坡国家体育场': 'Singapore National Stadium',
  '滨海艺术中心': 'Esplanade - Theatres on the Bay',
  '金沙会议展览中心': 'Sands Expo and Convention Centre',
  '苏州奥体中心体育馆': 'Suzhou Olympic Sports Center Gymnasium',
  '苏州文化艺术中心': 'Suzhou Culture and Arts Centre',
  '苏州保利大剧院': 'Suzhou Poly Grand Theatre',
  '苏州体育中心体育场': 'Suzhou Sports Center Stadium',
  '厦门嘉庚体育馆': 'Xiamen Jiageng Gymnasium',
  '厦门国际会展中心': 'Xiamen International Conference Center',
  '厦门闽南大戏院': 'Xiamen Minnan Theatre',
  '厦门体育中心体育场': 'Xiamen Sports Center Stadium',
  '青岛国信体育馆': 'Qingdao Guoxin Stadium',
  '青岛体育中心国信体育场': 'Qingdao Sports Center Guoxin Stadium',
  '青岛大剧院': 'Qingdao Grand Theatre',
  '青岛凤凰之声大剧院': 'Qingdao Phoenix Voice Grand Theatre',
  '大连体育中心体育馆': 'Dalian Sports Center Gymnasium',
  '大连大剧院': 'Dalian Grand Theatre',
  '大连国际会议中心大剧院': 'Dalian International Conference Center Grand Theatre',
  '大连星海广场': 'Dalian Xinghai Square',
  '昆明滇池国际会展中心': 'Kunming Dianchi International Convention Center',
  '昆明新亚洲体育城': 'Kunming New Asia Sports City',
  '昆明胜利堂剧院': 'Kunming Victory Theatre',
  '昆明海埂会堂': 'Kunming Haigeng Hall',
  '郑州奥林匹克体育中心': 'Zhengzhou Olympic Sports Center',
  '郑州国际会展中心': 'Zhengzhou International Convention Center',
  '郑州大剧院': 'Zhengzhou Grand Theatre',
  '郑州河南省体育中心': 'Henan Provincial Sports Center',
  '沈阳奥林匹克体育中心': 'Shenyang Olympic Sports Center',
  '沈阳盛京大剧院': 'Shenyang Shengjing Grand Theatre',
  '沈阳辽宁体育馆': 'Liaoning Gymnasium',
  '沈阳国际展览中心': 'Shenyang International Exhibition Center',
  '宁波奥体中心体育馆': 'Ningbo Olympic Sports Center Gymnasium',
  '宁波文化广场大剧院': 'Ningbo Cultural Square Grand Theatre',
  '宁波体育中心体育场': 'Ningbo Sports Center Stadium',
  '宁波逸夫剧院': 'Ningbo Yifu Theatre',
  '珠海国际航展中心': 'Zhuhai Airshow Center',
  '珠海大剧院（日月贝）': "Zhuhai Grand Theatre (Sun & Moon Shells)",
  '珠海体育中心体育场': 'Zhuhai Sports Center Stadium',
  '珠海华发中演大剧院': 'Zhuhai Huafa Zhongyan Grand Theatre',
  '佛山国际体育文化演艺中心': 'Foshan International Sports and Cultural Center',
  '佛山岭南明珠体育馆': 'Foshan Lingnan Pearl Gymnasium',
  '佛山南海体育馆': 'Foshan Nanhai Gymnasium',
  '佛山琼花大剧院': 'Foshan Qionghua Grand Theatre',
  '澳门威尼斯人金光综艺馆': "Venetian Macao's Cotai Arena",
  '澳门新濠影汇综艺馆': "Studio City Macau's Grand Theatre",
  '澳门文化中心': 'Macau Cultural Centre',
  '澳门百老汇舞台': 'Broadway Macau Theatre',
  '吉隆坡国家体育场': 'Bukit Jalil National Stadium',
  '亚通体育馆': 'Axiata Arena',
  '吉隆坡会展中心': 'Kuala Lumpur Convention Centre',
  '马来西亚国家剧院': 'Istana Budaya',
  '麦迪逊广场花园': 'Madison Square Garden',
  '巴克莱中心': 'Barclays Center',
  '无线电城音乐厅': 'Radio City Music Hall',
  '林肯中心': 'Lincoln Center',
  '阿波罗剧院': 'Apollo Theater',
  '斯台普斯中心（Crypto.com竞技场）': 'Crypto.com Arena (Staples Center)',
  '好莱坞碗': 'Hollywood Bowl',
  '道奇体育场': 'Dodger Stadium',
  '微软剧院': 'Microsoft Theater',
  '论坛体育馆': 'The Forum',
  'O2 体育馆': 'The O2 Arena',
  '温布利体育馆': 'Wembley Arena',
  '皇家阿尔伯特音乐厅': 'Royal Albert Hall',
  '伦敦体育场': 'London Stadium',
  '巴黎雅高竞技场': 'Accor Arena',
  '巴黎拉德芳斯体育馆': 'Paris La Défense Arena',
  '巴黎奥林匹亚音乐厅': "L'Olympia",
  '巴黎塞纳河音乐厅': 'La Seine Musicale',
  '悉尼奥林匹克公园': 'Sydney Olympic Park',
  '悉尼歌剧院': 'Sydney Opera House',
  '悉尼国际会议中心': 'International Convention Centre Sydney',
  '悉尼恩摩剧场': 'Enmore Theatre',
};

/**
 * Returns venues for a given city, with English labels if requested.
 */
export function getVenuesByCity(
  city: string,
  language: 'zh' | 'en' = 'zh',
): string[] {
  const cities = VENUES_BY_CITY[city];
  if (!cities) {
    // Fallback: partial match
    const matched = Object.entries(VENUES_BY_CITY).find(([key]) =>
      city.includes(key) || key.includes(city),
    );
    if (!matched) return [];

    if (language === 'en') {
      return matched[1].map((v) => VENUE_EN[v] || v);
    }
    return matched[1];
  }

  if (language === 'en') {
    return cities.map((v) => VENUE_EN[v] || v);
  }
  return cities;
}
